version: '3'
services:
  cursola:
    container_name: cursola
    build: 
      context: .
      dockerfile: Dockerfile

    tty: true
    volumes:
      - ./app:/usr/app
    command: /bin/bash
    ports:
      - 8000:8000
      